(defun main ()
  (let ((objective nil)
        (initial-task nil)
        (llm-model nil)
        (dotenv-extensions nil)
        (instance-name nil)
        (cooperative-mode nil)
        (join-existing-objective nil))
    (if (not objective)
        (progn
          (format t "~c[91m~c[1mNo initial task specified or found in environment.~%~c[0m~c[0m" #\ESC #\ESC #\ESC #\ESC)
          (print-help)
          (exit)))
    (values objective initial-task llm-model dotenv-extensions instance-name cooperative-mode join-existing-objective)))